// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAQ2QwLf0HiZTUVCnRNhzZqb6cVxxBC7o',
    appId: '1:20862213943:web:d0ea76064a126c08db84b2',
    messagingSenderId: '20862213943',
    projectId: 'exprimo-865e6',
    authDomain: 'exprimo-865e6.firebaseapp.com',
    storageBucket: 'exprimo-865e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1VRR44N4ZshSJxbk6ujFq8qIz2qFxEYI',
    appId: '1:20862213943:android:322d2c665f4d313fdb84b2',
    messagingSenderId: '20862213943',
    projectId: 'exprimo-865e6',
    storageBucket: 'exprimo-865e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK4B_RFcCyP1Hu332Lqv9n8igMFHhJ8Zo',
    appId: '1:20862213943:ios:1276a6e230ec4568db84b2',
    messagingSenderId: '20862213943',
    projectId: 'exprimo-865e6',
    storageBucket: 'exprimo-865e6.appspot.com',
    iosBundleId: 'com.example.exprimo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK4B_RFcCyP1Hu332Lqv9n8igMFHhJ8Zo',
    appId: '1:20862213943:ios:1276a6e230ec4568db84b2',
    messagingSenderId: '20862213943',
    projectId: 'exprimo-865e6',
    storageBucket: 'exprimo-865e6.appspot.com',
    iosBundleId: 'com.example.exprimo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAQ2QwLf0HiZTUVCnRNhzZqb6cVxxBC7o',
    appId: '1:20862213943:web:2f860ee09f77b397db84b2',
    messagingSenderId: '20862213943',
    projectId: 'exprimo-865e6',
    authDomain: 'exprimo-865e6.firebaseapp.com',
    storageBucket: 'exprimo-865e6.appspot.com',
  );
}
